### ISSUE TITLE
Add $("#element").dblclick();

### ISSUE THREAD

**Issue by jordiponsllaurado** [seleniumQuery/seleniumQuery#141]
Is there any plan to evaluate if `dblclick()` will be added to seleniumQuery or not?

**Comment by acdcjunior** [comment]
I can get it done by this weekend.

The only issue is to decide how to implement it. I believe using [`Actions`](http://selenium.googlecode.com/svn/trunk/docs/api/java/org/openqa/selenium/interactions/Actions.html) is the most natural way:

```java
Actions action = new Actions(driver);
WebElement element = ...;
action.doubleClick(element).perform();
```

Would you agree?

**Comment by jordiponsllaurado** [comment]
Yes, this is the way I implemented when I realised that dblclick() was not available yet.

**Comment by acdcjunior** [comment]
0.15.0 was deployed:

```
<dependency>
    <groupId>io.github.seleniumquery</groupId>
    <artifactId>seleniumquery</artifactId>
    <version>0.15.0</version>
</dependency>
```

I haven't updated the release page yet, but will today later.
