### ISSUE TITLE
SeleniumQuery considers good an invalid url after correct url

### ISSUE THREAD

**Issue by ghost** [seleniumQuery/seleniumQuery#144]
I'm currently testing with seleniumQuery and Firefox 38.7 a test that checks for an invalid URL, then for a valid one, then for an invalid one, as it follows:

```
browser.get("InvalidURL");
browser.get(validURL);
browser.get("invalidURL");
```

The first one throws an `WebDriverException: Target URL InvalidURL is not well-formed.` which is expected. The second one opens the validURL as expected. But the third one, instead of trying to open "InvalidURL", i opens "www.invalidurl.com", which is a valid URL, making the test to fail.

Any chance on how to fix that?

Thanks.

**Comment by acdcjunior** [comment]
@pboix22 I think this problem is related to [Selenium](https://github.com/SeleniumHQ/selenium) directly, not seleniumQuery. Isn't it? If so, this issue is better placed at https://github.com/SeleniumHQ/selenium (because we probably can't do much to work around it through seleniumQuery).

Would you agree?

**Comment by pboix22** [comment]
Well, we had this test case running and passing with Selenium before
starting the migration to SeleniumQuery. We haven't updated the browser
either.

I can try running the same test again with Selenium to discard any relation
with it. I'll keep you posted on the issue :)

Thanks!

**Comment by acdcjunior** [comment]
By all means, if you think this is a seleniumQuery problema, let's investigar.
I'm asking because `get(String)` is the name of a method in `WebDriver`, seleniumQuery hás no method with that signature (so I don't even know where to start).

**Comment by acdcjunior** [comment]
@pboix22 Any news on this issue? Selenium has updated to 2.53.1 and seleniumQuery to 0.16.0.

**Comment by acdcjunior** [comment]
I'm closing this issue. If you have any problems, feel free to comment here or open another.
