### ISSUE TITLE
[Question] multiple condicionals

### ISSUE THREAD

**Issue by jordiponsllaurado** [seleniumQuery/seleniumQuery#146]
Is there any way to check if some element has one condition or another one? 

For example If I have an element that has a text or a value attribute it would be possible to sendKeys to that element and wait until the value or the text are the expected ones, something like `$(element).val(text).waitUntil().text().isEqualTo(text).or().val().isEqualTo(text)`

**Comment by acdcjunior** [comment]
Hmm.. today, the best we have for your case is `.waitUntil().text().matches("regex")`.

You then have to write a regex that would match one text or another. Like this:

```
$(element).val(text).waitUntil().text().matches("abc|xyz");
```

This would wait until `$(element).text()` returns either `"abc"` or `"xyz"`.

I understand this is suboptimal, but it does is something you can use right away.

PS.: If your string has chars that are considered special in regexes (like `[` or `(`), you'd have to escape them.

**Comment by jordiponsllaurado** [comment]
What if I don't know if I need to use val() or text() ? Is there any way to do the waituntil?

**Comment by acdcjunior** [comment]
Ah, I didn't notice the second `.isEqualTo()` was actually called on `.val()`.

I'm afraid the only way you can do it right now is something like:

```java
$(element).val(text);
try {
	$(element).waitUntil().text().isEqualTo(text);
} catch (io.github.seleniumquery.wait.SeleniumQueryTimeoutException ignored) {
	$(element).waitUntil().val().isEqualTo(text);
}
```

If you use it a lot, you can create a method and reuse it or even [create a plugin](https://github.com/acdcjunior/seleniumQuery-showcase/tree/master/src/main/java/plugin).

---

About adding something directly to seleniumQuery to make this easier, it's tricky. Other frameworks implement a method that [takes Hamcrest matchers as arguments](http://stackoverflow.com/questions/152714/multiple-correct-results-with-hamcrest-is-there-an-or-matcher) (like JUnit's `assertThat()` method). I guess this would be a way out.

**Comment by jordiponsllaurado** [comment]
I will use the snippet and if I see that is useful then I will create a plugin ;)
