### ISSUE TITLE
[Question] Select element inside iframe

### ISSUE THREAD

**Issue by jordiponsllaurado** [seleniumQuery/seleniumQuery#147]
How SeleniumQuery interacts with Iframes?

If I want to get an element inside an iframe how can I do it?

For example If I want to interact with the element "one" inside the iframe "contentFrame":
**Index.hml**
```
<html>
    <body>
        <p> Hello </p>
        <iframe id='contentFrame' src=".../frame.html"></iframe>
    </body>
</html>
```
**iframe.html**
```
<html>
<head>
    <meta charset="utf-8">
    <title>iframe.html example</title>
</head>
<body>
    <button id="one">some content</button>
</body>
</html>
```

In this situation how can I click the button?

It will be great if we can use `.contents()` for example

**Comment by acdcjunior** [comment]
You could:

```java
$.driver().get().switchTo().frame($("#contentFrame").get(0));
```

Then interact normally with any element within the frame:

```java
$("#one").click();
```

About `.contents()` could you be more specific about a possible use for it (from a Selenium point of view)?

**Comment by jordiponsllaurado** [comment]
for doing some stuff like here:
http://stackoverflow.com/questions/15343955/jquery-select-element-inside-iframe-which-is-inside-iframe

But I think that the `switchTo()` is better and more clean :)
