### ISSUE TITLE
[Question] Custom Timeout

### ISSUE THREAD

**Issue by jordiponsllaurado** [seleniumQuery/seleniumQuery#148]
I have some tests that fails because the environment that I use is extremely slow so the tests throw this exception:

> Caused by: org.openqa.selenium.TimeoutException: Timed out after 10 seconds waiting for io.github.seleniumquery.wait.WaitFunction@3e67f6a8

Is there any way I can increate the timeout from 10 seconds to 60, like the pageLoadTimeout?

**Comment by acdcjunior** [comment]
The `.waitUntil()` function accepts a `long` argument that would be a custom timeout (in ms).

You can specify globally, for all `.waitUntil()`s, by changing the `WAITUNTIL_TIMEOUT` property in the `seleniumQuery.properties` file (you can create one if you don't have it).

The [showcase project](https://github.com/acdcjunior/seleniumQuery-showcase/) has an example of how the [`seleniumQuery.properties` file](https://github.com/acdcjunior/seleniumQuery-showcase/blob/master/src/main/resources/seleniumQuery.properties) works.


---

In other words, the code:

```java
// waits for the default (10s) or the specified at WAITUNTIL_TIMEOUT seleniumQuery.properties
$(element).waitUntil().text().isEqualTo("something");
```

- Waits for the default time: 10s (as specified, hardcoded, in [SeleniumQueryConfig class](https://github.com/seleniumQuery/seleniumQuery/blob/master/src/main/java/io/github/seleniumquery/SeleniumQueryConfig.java#L45))
- Or for the time specified in the `WAITUNTIL_TIMEOUT` property in the `seleniumQuery.properties` file (if you have one in your classpath)

And the code

```java
// waits for 15s
$(element).waitUntil(15000).text().isEqualTo("something");
```

- Waits for the specified time, in ms.

**Comment by jordiponsllaurado** [comment]
The seleniumQuery.properties it worked.
Thanks!
