### ISSUE TITLE
.is() function exception

### ISSUE THREAD

**Issue by jordiponsllaurado** [seleniumQuery/seleniumQuery#149]
After updating from version 0.13.0 to 0.15.0 my tests fail when I try to perform `$(element).waitUntil().is(":visible");`, it give me the following error message:

> java.lang.IncompatibleClassChangeError: Found class io.github.seleniumquery.SeleniumQueryObject, but interface was expected

I checked if the element exists and how many elements it returns the `$(element)` and it only returns one element, also I tried `$(element).click() `and it works.

Do you know why it's failing?

**Comment by acdcjunior** [comment]
This is happening because `io.github.seleniumquery.SeleniumQueryObject` used to be a class and now it's an interface. If you recompile your code (that uses seleniumQuery), this problem should go away.

**Comment by jordiponsllaurado** [comment]
I recompiled all the code and still happening. I think that the error is not in the compilation because if thats the problem it should fail with the other methods like `click()`, but the other ones works perfectly.

**Comment by jordiponsllaurado** [comment]
Ok I solved the problems, we had a bit of chaos in our pom files so I fixed and recompiled and now it works, so It was a compiling problem jejej
