### ISSUE TITLE
How to use EventFiringWebDriver

### ISSUE THREAD

**Issue by gmkumar2005** [seleniumQuery/seleniumQuery#208]
How can I attach EventFiringWebDriver to the webdriver.
EventFiringWebDriver is used to listen to the events in the browserdriver. 
It is a wrapper over the webdriver initited as below

 EventFiringWebDriver efwd = new EventFiringWebDriver(ie11);
    efwd.register(new CustomEventLogger());

How can I get the efwd  when i access the driver using $.driver().get()

Thanks

**Comment by acdcjunior** [comment]
Oh, hey, sorry for the delay. I wanted to test before answering.

And I actually found out it is a bit too complicated for you to do it, but here's one way:

```java
// create a LOCAL driver
SeleniumQueryBrowser chrome = new SeleniumQueryBrowser();
chrome.$.driver().useChrome().headless().autoDriverDownload().autoQuitDriver();
// get the driver
WebDriver myDriver = chrome.$.driver().get();
// wrap it
EventFiringWebDriver efwd = new EventFiringWebDriver(myDriver);
// register the listener (can be done later as well)
efwd.register(new CustomEventLogger());
// configure seleniumQuery GLOBAL to use the "wrapped" version as driver
$.driver().use(efwd);

// now proceed as usual
$.url("http://www.google.com");
```

It should work if you have immediate needs.

But I'd like to make it easier for us to use it. I can implement it in the API. If you have any suggestions I'd be glad to hear them.

**Comment by gmkumar2005** [comment]
Thanks for the reply. I tried this option. It does not work, apparently because $.driver().use(efwd) destroys existing instance of webdriver, so $.url("http://www.google.com");  failed.

For now I have extended the driverBuilder. 

` 
public class ChromeDriverBuilder extends
    io.github.seleniumquery.browser.driver.builders.ChromeDriverBuilder {

  private WebDriverEventListener webDriverEventListener;

  @Override
  protected WebDriver build() {

    WebDriver chromeWebDriver;
    if (webDriverEventListener != null) {
      WebDriver webDriver = super.build();
      EventFiringWebDriver efwd = new EventFiringWebDriver(webDriver);
      efwd.register(webDriverEventListener);
      chromeWebDriver = efwd;
    } else {
      chromeWebDriver = super.build();
    }
    return chromeWebDriver;
  }

  public io.github.seleniumquery.browser.driver.builders.ChromeDriverBuilder withEventListener(
      WebDriverEventListener eventListener) {
    this.webDriverEventListener = eventListener;
    return this;
  }
}
`

**The usage is**

`  ChromeDriverBuilder driverBuilder = new ChromeDriverBuilder();
    driverBuilder.headless();
    driverBuilder.autoDriverDownload();
    driverBuilder.autoQuitDriver();
    driverBuilder.withEventListener(new SeleniumEventLogger());
    driver = driverBuilder.build();
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.manage().window().maximize();
    driver.manage().window().fullscreen();
    $.driver().use(driver); `

It would be nice if you can add this in all the driverbuilders. I could send a PR but right now I am busy.

**Comment by acdcjunior** [comment]
That's a great suggestion, thank you! I will try to implement it this weekend, ok? I will reference this issue in the commit. There's no pressing need for you to write a PR, but if you do, feel free and I'd gladly accept it!

**Comment by acdcjunior** [comment]
JSYK, 0.19.0 has been released, containing your patch: https://github.com/seleniumQuery/seleniumQuery/releases/tag/0.19.0

Thanks again!
